name: Lerna

on: [push]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: yarn install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: lerna bootstrap
        uses: m19c/action-lerna@1.0.0
        with:
          args: "bootstrap"
      - name: lerna test
        uses: m19c/action-lerna@1.0.0
        with:
          args: "test"
