name: Lerna

on: [push]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x] # 12.x, 13.x, 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.0
    - name: yarn install
        with:
          cmd: install
    - name: lerna bootstrap && lerna test
      uses: m19c/action-lerna@1.0.0

