name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn run lerna bootstrap
      - run: yarn run lerna run test
